# Generated by Django 5.2.16 on 2026-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_scheduled_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='ad_budget',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='address_city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='address_country',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='address_state',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='address_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='address_zip',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='biggest_challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='current_revenue',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='ecommerce_goal',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='has_existing_shopify_store',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='previous_experience',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='success_definition',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='vertical_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='weekly_time_investment',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='desired_niche',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='vertical_industry',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
