# Generated by Django 5.2.16 on 2026-07-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_mark_existing_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='biggest_challenges_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
