# Generated by Django 5.2.14 on 2026-07-23 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coach', models.BooleanField(default=True, help_text='Allow this staff user to join the coach desk and live chats.')),
                ('is_available', models.BooleanField(default=True, help_text='Shown as available for new waiting sessions.')),
                ('max_concurrent', models.PositiveSmallIntegerField(default=5, help_text='Max live merchant sessions this coach can hold at once.')),
                ('display_name', models.CharField(blank=True, help_text='Optional name shown to merchants (defaults to user full name).', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach profile',
                'verbose_name_plural': 'Coach profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='CoachSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('bot', 'BrandBox Coach Agent'), ('waiting', 'Waiting for coach'), ('live', 'Live with coach'), ('closed', 'Closed')], db_index=True, default='bot', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_merchant_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_coach_message_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_coach_sessions', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('merchant', 'Merchant'), ('agent', 'BrandBox Coach Agent'), ('coach', 'Coach'), ('system', 'System')], max_length=16)),
                ('body', models.TextField()),
                ('guide_title', models.CharField(blank=True, max_length=255)),
                ('guide_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='coach.coachsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoachAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('claim', 'Claim'), ('reassign', 'Reassign'), ('leave', 'Leave')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='coach.coachsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coachsession',
            index=models.Index(fields=['status', '-updated_at'], name='coach_coach_status_627112_idx'),
        ),
        migrations.AddIndex(
            model_name='coachsession',
            index=models.Index(fields=['merchant', '-updated_at'], name='coach_coach_merchan_3d2def_idx'),
        ),
        migrations.AddIndex(
            model_name='coachmessage',
            index=models.Index(fields=['session', 'id'], name='coach_coach_session_9b22d9_idx'),
        ),
    ]
