# Generated by Django 5.2.14 on 2026-07-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachassignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assignment log', 'verbose_name_plural': 'Assignment logs'},
        ),
        migrations.AlterModelOptions(
            name='coachmessage',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='coachprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='coachsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Chat session', 'verbose_name_plural': 'Chat sessions'},
        ),
        migrations.AlterField(
            model_name='coachmessage',
            name='role',
            field=models.CharField(choices=[('merchant', 'Merchant'), ('agent', 'Coach Agent'), ('coach', 'Coach'), ('system', 'System')], max_length=16),
        ),
        migrations.AlterField(
            model_name='coachsession',
            name='status',
            field=models.CharField(choices=[('bot', 'Agent'), ('waiting', 'Waiting'), ('live', 'Live'), ('closed', 'Closed')], db_index=True, default='bot', max_length=16),
        ),
    ]
