# Generated by Django 5.2.16 on 2026-07-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('refund', 'Refund Policy')], help_text='Which policy this is (fixed URL).', max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='HTML allowed (headings, paragraphs, lists). Staff-only content.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished pages show a simple unavailable message publicly.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal page',
                'verbose_name_plural': 'Legal pages',
                'ordering': ['key'],
            },
        ),
    ]
