# Generated by Django 5.2.16 on 2026-07-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_affiliate_register_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateapplication',
            name='promotion_other',
            field=models.TextField(blank=True, help_text='Required when promotion plan is Other — describe the strategy.'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='key',
            field=models.CharField(choices=[('home', 'Home'), ('contact', 'Contact'), ('about', 'About Us'), ('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('refund', 'Refund Policy'), ('disclaimer', 'Disclaimer'), ('affiliate', 'Affiliate'), ('affiliate_apply', 'Affiliate Register')], help_text='Which public page these tags apply to.', max_length=32, unique=True),
        ),
    ]
