# Generated by Django 5.2.16 on 2026-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_affiliate_promotion_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateapplication',
            name='activity_other',
            field=models.CharField(blank=True, help_text='Required when current activity is Other.', max_length=120),
        ),
        migrations.AddField(
            model_name='affiliateapplication',
            name='current_activity',
            field=models.CharField(choices=[('student', 'Student'), ('freelancer', 'Freelancer'), ('influencer', 'Influencer / Creator'), ('blogger', 'Blogger'), ('marketer', 'Marketer'), ('agency', 'Agency owner'), ('entrepreneur', 'Entrepreneur / Founder'), ('coach', 'Coach / Educator'), ('employee', 'In-house employee'), ('other', 'Other')], default='freelancer', max_length=32),
        ),
    ]
