# Generated by Django 5.2.14 on 2026-07-23 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, help_text='Short blurb for cards and search snippets.', max_length=320)),
                ('body', models.TextField(help_text='HTML allowed (headings, paragraphs, lists, embeds).')),
                ('is_published', models.BooleanField(default=True)),
                ('is_coming_soon', models.BooleanField(default=False, help_text='Show a Coming soon note when the underlying feature is incomplete.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hero_image', models.ImageField(blank=True, help_text='Optional screenshot or illustration at top of article.', null=True, upload_to='help/heroes/')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube/Vimeo or direct video URL.', max_length=500)),
                ('video_file', models.FileField(blank=True, help_text='Optional uploaded video file.', null=True, upload_to='help/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help article',
                'verbose_name_plural': 'Help articles',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='help', help_text='Material Symbols icon name, e.g. rocket_launch', max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Help category',
                'verbose_name_plural': 'Help categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='help/attachments/')),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='help.helparticle')),
            ],
            options={
                'verbose_name': 'Article image / screenshot',
                'verbose_name_plural': 'Article images / screenshots',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_helpful', models.BooleanField()),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='help.helparticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article feedback',
                'verbose_name_plural': 'Article feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='helparticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help.helpcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='helparticle',
            unique_together={('category', 'slug')},
        ),
    ]
